services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - todo_pg_data:/var/lib/postgresql/data
    networks:
      - todo_net

  app:
    image: tg/todo-app:1.1
    depends_on:
      - db
    environment:
      SERVER_PORT: 8080
      DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
    ports:
      - "${APP_PORT}:8080"
    networks:
      - todo_net

volumes:
  todo_pg_data:

networks:
  todo_net:
    driver: bridge
